#!/bin/python3

import math
import os
import random
import re
import sys



if __name__ == '__main__':
    N = int(input())

if N%2!=0:
    print("weird")
elif N>2 and N<5:
    print("Not weird")
elif N>6 and N<20:
    print("weird")
elif N>20:
    print("Not weird")   
